#ifndef SIMPLE_DB_C_CONSTS_H
#define SIMPLE_DB_C_CONSTS_H

#include "stdlib.h"

#define TABLE_MAX_PAGES 100
#define COLUMN_USERNAME_SIZE 32
#define COLUMN_EMAIL_SIZE 255

#define PAGE_SIZE 4096

#endif  // SIMPLE_DB_C_CONSTS_H
